importCpg("/data/DataLACP/wangke/recorebench/workspace/dynamic-tp/cpg.bin.zip")
cpg.block.where(_.file.nameExact("core/src/main/java/com/dtp/core/context/BaseNotifyCtx.java")).l
cpg.file.nameExact("core/src/main/java/com/dtp/core/context/BaseNotifyCtx.java").foreach(println)















// Generated by delombok at Sun Jun 08 05:46:52 UTC 2025
package com.dtp.core.context;

import com.dtp.core.notify.capture.CapturedExecutor;
import com.dtp.core.support.ExecutorWrapper;
import com.dtp.common.entity.NotifyItem;
import com.dtp.common.em.NotifyItemEnum;

/**
 * BaseNotifyCtx related
 *
 * @author yanhom
 * @since 1.0.8
 */
public class BaseNotifyCtx {
    private ExecutorWrapper executorWrapper;
    private CapturedExecutor capturedExecutor;
    private NotifyItem notifyItem;

    public BaseNotifyCtx() {
    }

    public BaseNotifyCtx(ExecutorWrapper wrapper, NotifyItem notifyItem) {
        this.executorWrapper = wrapper;
        this.capturedExecutor = new CapturedExecutor(wrapper.getExecutor());
        this.notifyItem = notifyItem;
    }

    public NotifyItemEnum getNotifyItemEnum() {
        return NotifyItemEnum.of(notifyItem.getType());
    }

    @java.lang.SuppressWarnings("all")
    public ExecutorWrapper getExecutorWrapper() {
        return this.executorWrapper;
    }

    @java.lang.SuppressWarnings("all")
    public CapturedExecutor getCapturedExecutor() {
        return this.capturedExecutor;
    }

    @java.lang.SuppressWarnings("all")
    public NotifyItem getNotifyItem() {
        return this.notifyItem;
    }

    @java.lang.SuppressWarnings("all")
    public void setExecutorWrapper(final ExecutorWrapper executorWrapper) {
        this.executorWrapper = executorWrapper;
    }

    @java.lang.SuppressWarnings("all")
    public void setCapturedExecutor(final CapturedExecutor capturedExecutor) {
        this.capturedExecutor = capturedExecutor;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotifyItem(final NotifyItem notifyItem) {
        this.notifyItem = notifyItem;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BaseNotifyCtx)) return false;
        final BaseNotifyCtx other = (BaseNotifyCtx) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$executorWrapper = this.getExecutorWrapper();
        final java.lang.Object other$executorWrapper = other.getExecutorWrapper();
        if (this$executorWrapper == null ? other$executorWrapper != null : !this$executorWrapper.equals(other$executorWrapper)) return false;
        final java.lang.Object this$capturedExecutor = this.getCapturedExecutor();
        final java.lang.Object other$capturedExecutor = other.getCapturedExecutor();
        if (this$capturedExecutor == null ? other$capturedExecutor != null : !this$capturedExecutor.equals(other$capturedExecutor)) return false;
        final java.lang.Object this$notifyItem = this.getNotifyItem();
        final java.lang.Object other$notifyItem = other.getNotifyItem();
        if (this$notifyItem == null ? other$notifyItem != null : !this$notifyItem.equals(other$notifyItem)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BaseNotifyCtx;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $executorWrapper = this.getExecutorWrapper();
        result = result * PRIME + ($executorWrapper == null ? 43 : $executorWrapper.hashCode());
        final java.lang.Object $capturedExecutor = this.getCapturedExecutor();
        result = result * PRIME + ($capturedExecutor == null ? 43 : $capturedExecutor.hashCode());
        final java.lang.Object $notifyItem = this.getNotifyItem();
        result = result * PRIME + ($notifyItem == null ? 43 : $notifyItem.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "BaseNotifyCtx(executorWrapper=" + this.getExecutorWrapper() + ", capturedExecutor=" + this.getCapturedExecutor() + ", notifyItem=" + this.getNotifyItem() + ")";
    }
}













/data/DataLACP/wangke/recorebench/repo/repo/Geyser/core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java


importCpg("/data/DataLACP/wangke/recorebench/workspace/Geyser/cpg.bin.zip")
cpg.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java").foreach(println)
cpg.file.foreach(println)


joern> cpg.file.name.foreach(println)
ap/src/main/java/org/geysermc/geyser/processor/BlockEntityProcessor.java
ap/src/main/java/org/geysermc/geyser/processor/ClassProcessor.java
ap/src/main/java/org/geysermc/geyser/processor/CollisionRemapperProcessor.java
ap/src/main/java/org/geysermc/geyser/processor/PacketTranslatorProcessor.java
ap/src/main/java/org/geysermc/geyser/processor/SoundHandlerProcessor.java
api/src/main/java/org/geysermc/geyser/api/GeyserApi.java
api/src/main/java/org/geysermc/geyser/api/bedrock/camera/CameraShake.java
api/src/main/java/org/geysermc/geyser/api/block/custom/CustomBlockData.java
api/src/main/java/org/geysermc/geyser/api/block/custom/CustomBlockPermutation.java
api/src/main/java/org/geysermc/geyser/api/block/custom/CustomBlockState.java
api/src/main/java/org/geysermc/geyser/api/block/custom/NonVanillaCustomBlockData.java
api/src/main/java/org/geysermc/geyser/api/block/custom/component/BoxComponent.java
api/src/main/java/org/geysermc/geyser/api/block/custom/component/CustomBlockComponents.java
api/src/main/java/org/geysermc/geyser/api/block/custom/component/GeometryComponent.java
api/src/main/java/org/geysermc/geyser/api/block/custom/component/MaterialInstance.java
api/src/main/java/org/geysermc/geyser/api/block/custom/component/PlacementConditions.java
api/src/main/java/org/geysermc/geyser/api/block/custom/component/TransformationComponent.java
api/src/main/java/org/geysermc/geyser/api/block/custom/nonvanilla/JavaBlockItem.java
api/src/main/java/org/geysermc/geyser/api/block/custom/nonvanilla/JavaBlockState.java
api/src/main/java/org/geysermc/geyser/api/block/custom/nonvanilla/JavaBoundingBox.java
api/src/main/java/org/geysermc/geyser/api/block/custom/property/CustomBlockProperty.java
api/src/main/java/org/geysermc/geyser/api/block/custom/property/PropertyType.java
api/src/main/java/org/geysermc/geyser/api/command/Command.java
api/src/main/java/org/geysermc/geyser/api/command/CommandExecutor.java
api/src/main/java/org/geysermc/geyser/api/command/CommandSource.java
api/src/main/java/org/geysermc/geyser/api/connection/GeyserConnection.java
api/src/main/java/org/geysermc/geyser/api/entity/type/GeyserEntity.java
api/src/main/java/org/geysermc/geyser/api/entity/type/player/GeyserPlayerEntity.java
api/src/main/java/org/geysermc/geyser/api/event/EventBus.java
api/src/main/java/org/geysermc/geyser/api/event/EventRegistrar.java
api/src/main/java/org/geysermc/geyser/api/event/EventSubscriber.java
api/src/main/java/org/geysermc/geyser/api/event/ExtensionEventBus.java
api/src/main/java/org/geysermc/geyser/api/event/ExtensionEventSubscriber.java
api/src/main/java/org/geysermc/geyser/api/event/bedrock/ClientEmoteEvent.java
api/src/main/java/org/geysermc/geyser/api/event/bedrock/SessionDisconnectEvent.java
api/src/main/java/org/geysermc/geyser/api/event/bedrock/SessionInitializeEvent.java
api/src/main/java/org/geysermc/geyser/api/event/bedrock/SessionJoinEvent.java
api/src/main/java/org/geysermc/geyser/api/event/bedrock/SessionLoadResourcePacksEvent.java
api/src/main/java/org/geysermc/geyser/api/event/bedrock/SessionLoginEvent.java
api/src/main/java/org/geysermc/geyser/api/event/connection/ConnectionEvent.java
api/src/main/java/org/geysermc/geyser/api/event/connection/GeyserBedrockPingEvent.java
api/src/main/java/org/geysermc/geyser/api/event/downstream/ServerDefineCommandsEvent.java
api/src/main/java/org/geysermc/geyser/api/event/java/ServerDefineCommandsEvent.java
api/src/main/java/org/geysermc/geyser/api/event/lifecycle/GeyserDefineCommandsEvent.java
api/src/main/java/org/geysermc/geyser/api/event/lifecycle/GeyserDefineCustomBlocksEvent.java
api/src/main/java/org/geysermc/geyser/api/event/lifecycle/GeyserDefineCustomItemsEvent.java
api/src/main/java/org/geysermc/geyser/api/event/lifecycle/GeyserDefineCustomSkullsEvent.java
api/src/main/java/org/geysermc/geyser/api/event/lifecycle/GeyserLoadResourcePacksEvent.java
api/src/main/java/org/geysermc/geyser/api/event/lifecycle/GeyserPostInitializeEvent.java
api/src/main/java/org/geysermc/geyser/api/event/lifecycle/GeyserPreInitializeEvent.java
api/src/main/java/org/geysermc/geyser/api/event/lifecycle/GeyserShutdownEvent.java
api/src/main/java/org/geysermc/geyser/api/extension/Extension.java
api/src/main/java/org/geysermc/geyser/api/extension/ExtensionDescription.java
api/src/main/java/org/geysermc/geyser/api/extension/ExtensionLoader.java
api/src/main/java/org/geysermc/geyser/api/extension/ExtensionLogger.java
api/src/main/java/org/geysermc/geyser/api/extension/ExtensionManager.java
api/src/main/java/org/geysermc/geyser/api/extension/exception/InvalidDescriptionException.java
api/src/main/java/org/geysermc/geyser/api/extension/exception/InvalidExtensionException.java
api/src/main/java/org/geysermc/geyser/api/item/custom/CustomItemData.java
api/src/main/java/org/geysermc/geyser/api/item/custom/CustomItemOptions.java
api/src/main/java/org/geysermc/geyser/api/item/custom/CustomRenderOffsets.java
api/src/main/java/org/geysermc/geyser/api/item/custom/NonVanillaCustomItemData.java
api/src/main/java/org/geysermc/geyser/api/network/AuthType.java
api/src/main/java/org/geysermc/geyser/api/network/BedrockListener.java
api/src/main/java/org/geysermc/geyser/api/network/RemoteServer.java
api/src/main/java/org/geysermc/geyser/api/pack/PackCodec.java
api/src/main/java/org/geysermc/geyser/api/pack/PathPackCodec.java
api/src/main/java/org/geysermc/geyser/api/pack/ResourcePack.java
api/src/main/java/org/geysermc/geyser/api/pack/ResourcePackManifest.java
api/src/main/java/org/geysermc/geyser/api/util/CreativeCategory.java
api/src/main/java/org/geysermc/geyser/api/util/PlatformType.java
api/src/main/java/org/geysermc/geyser/api/util/TriState.java
bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeeCompressionDisabler.java
bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeeConfiguration.java
bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeeDumpInfo.java
bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeeInjector.java
bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeeLogger.java
bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeeMain.java
bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeePingPassthrough.java
bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeePlugin.java
bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeeUpdateListener.java
bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/command/BungeeCommandSource.java
bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/command/GeyserBungeeCommandExecutor.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/GeyserFabricConfiguration.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/GeyserFabricDumpInfo.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/GeyserFabricLogger.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/GeyserFabricMain.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/GeyserFabricMod.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/GeyserFabricUpdateListener.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/GeyserServerPortGetter.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/ModPingPassthrough.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/command/FabricCommandSender.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/command/GeyserFabricCommandExecutor.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/mixin/client/IntegratedServerMixin.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/mixin/server/MinecraftDedicatedServerMixin.java
bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/world/GeyserFabricWorldManager.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserPaperLogger.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserPaperPingPassthrough.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotCompressionDisabler.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotConfiguration.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotDumpInfo.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotInjector.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotLogger.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotMain.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotPingPassthrough.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotPlugin.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotUpdateListener.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotVersionChecker.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/PaperAdventure.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/ReflectedNames.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/command/GeyserBrigadierSupport.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/command/GeyserPaperCommandListener.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/command/GeyserSpigotCommandExecutor.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/command/GeyserSpigotCommandManager.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/command/SpigotCommandSource.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/world/GeyserPistonListener.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/world/GeyserSpigotBlockPlaceListener.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/world/manager/GeyserSpigotLegacyNativeWorldManager.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/world/manager/GeyserSpigotNativeWorldManager.java
bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/world/manager/GeyserSpigotWorldManager.java
bootstrap/standalone/src/main/java/org/geysermc/geyser/platform/standalone/GeyserStandaloneBootstrap.java
bootstrap/standalone/src/main/java/org/geysermc/geyser/platform/standalone/GeyserStandaloneConfiguration.java
bootstrap/standalone/src/main/java/org/geysermc/geyser/platform/standalone/GeyserStandaloneDumpInfo.java
bootstrap/standalone/src/main/java/org/geysermc/geyser/platform/standalone/GeyserStandaloneLogger.java
bootstrap/standalone/src/main/java/org/geysermc/geyser/platform/standalone/gui/ANSIColor.java
bootstrap/standalone/src/main/java/org/geysermc/geyser/platform/standalone/gui/ColorPane.java
bootstrap/standalone/src/main/java/org/geysermc/geyser/platform/standalone/gui/GeyserStandaloneGUI.java
bootstrap/standalone/src/main/java/org/geysermc/geyser/platform/standalone/gui/GraphPanel.java
bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/GeyserVelocityCompressionDisabler.java
bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/GeyserVelocityConfiguration.java
bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/GeyserVelocityDumpInfo.java
bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/GeyserVelocityInjector.java
bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/GeyserVelocityLogger.java
bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/GeyserVelocityMain.java
bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/GeyserVelocityPingPassthrough.java
bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/GeyserVelocityPlugin.java
bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/GeyserVelocityUpdateListener.java
bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/command/GeyserVelocityCommandExecutor.java
bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/command/VelocityCommandSource.java
common/src/main/java/org/geysermc/floodgate/crypto/AesCipher.java
common/src/main/java/org/geysermc/floodgate/crypto/AesKeyProducer.java
common/src/main/java/org/geysermc/floodgate/crypto/Base64Topping.java
common/src/main/java/org/geysermc/floodgate/crypto/FloodgateCipher.java
common/src/main/java/org/geysermc/floodgate/crypto/KeyProducer.java
common/src/main/java/org/geysermc/floodgate/crypto/Topping.java
common/src/main/java/org/geysermc/floodgate/news/NewsItem.java
common/src/main/java/org/geysermc/floodgate/news/NewsItemAction.java
common/src/main/java/org/geysermc/floodgate/news/NewsItemMessage.java
common/src/main/java/org/geysermc/floodgate/news/NewsType.java
common/src/main/java/org/geysermc/floodgate/news/data/AnnouncementData.java
common/src/main/java/org/geysermc/floodgate/news/data/BuildSpecificData.java
common/src/main/java/org/geysermc/floodgate/news/data/CheckAfterData.java
common/src/main/java/org/geysermc/floodgate/news/data/ConfigSpecificData.java
common/src/main/java/org/geysermc/floodgate/news/data/ItemData.java
common/src/main/java/org/geysermc/floodgate/pluginmessage/PluginMessageChannels.java
common/src/main/java/org/geysermc/floodgate/util/BedrockData.java
common/src/main/java/org/geysermc/floodgate/util/DeviceOs.java
common/src/main/java/org/geysermc/floodgate/util/FloodgateInfoHolder.java
common/src/main/java/org/geysermc/floodgate/util/InputMode.java
common/src/main/java/org/geysermc/floodgate/util/InvalidFormatException.java
common/src/main/java/org/geysermc/floodgate/util/LinkedPlayer.java
common/src/main/java/org/geysermc/floodgate/util/UiProfile.java
common/src/main/java/org/geysermc/floodgate/util/WebsocketEventType.java
core/src/main/java/org/geysermc/geyser/Constants.java
core/src/main/java/org/geysermc/geyser/FloodgateKeyLoader.java
core/src/main/java/org/geysermc/geyser/GeyserBootstrap.java
core/src/main/java/org/geysermc/geyser/GeyserImpl.java
core/src/main/java/org/geysermc/geyser/GeyserLogger.java
core/src/main/java/org/geysermc/geyser/GeyserMain.java
core/src/main/java/org/geysermc/geyser/command/GeyserCommand.java
core/src/main/java/org/geysermc/geyser/command/GeyserCommandExecutor.java
core/src/main/java/org/geysermc/geyser/command/GeyserCommandManager.java
core/src/main/java/org/geysermc/geyser/command/GeyserCommandSource.java
core/src/main/java/org/geysermc/geyser/command/defaults/AdvancedTooltipsCommand.java
core/src/main/java/org/geysermc/geyser/command/defaults/AdvancementsCommand.java
core/src/main/java/org/geysermc/geyser/command/defaults/ConnectionTestCommand.java
core/src/main/java/org/geysermc/geyser/command/defaults/DumpCommand.java
core/src/main/java/org/geysermc/geyser/command/defaults/ExtensionsCommand.java
core/src/main/java/org/geysermc/geyser/command/defaults/HelpCommand.java
core/src/main/java/org/geysermc/geyser/command/defaults/ListCommand.java
core/src/main/java/org/geysermc/geyser/command/defaults/OffhandCommand.java
core/src/main/java/org/geysermc/geyser/command/defaults/ReloadCommand.java
core/src/main/java/org/geysermc/geyser/command/defaults/SettingsCommand.java
core/src/main/java/org/geysermc/geyser/command/defaults/StatisticsCommand.java
core/src/main/java/org/geysermc/geyser/command/defaults/StopCommand.java
core/src/main/java/org/geysermc/geyser/command/defaults/VersionCommand.java
core/src/main/java/org/geysermc/geyser/configuration/EmoteOffhandWorkaroundOption.java
core/src/main/java/org/geysermc/geyser/configuration/GeyserConfiguration.java
core/src/main/java/org/geysermc/geyser/configuration/GeyserCustomSkullConfiguration.java
core/src/main/java/org/geysermc/geyser/configuration/GeyserJacksonConfiguration.java
core/src/main/java/org/geysermc/geyser/dump/BootstrapDumpInfo.java
core/src/main/java/org/geysermc/geyser/dump/DumpInfo.java
core/src/main/java/org/geysermc/geyser/entity/EntityDefinition.java
core/src/main/java/org/geysermc/geyser/entity/EntityDefinitions.java
core/src/main/java/org/geysermc/geyser/entity/GeyserDirtyMetadata.java
core/src/main/java/org/geysermc/geyser/entity/attribute/GeyserAttributeType.java
core/src/main/java/org/geysermc/geyser/entity/factory/EntityFactory.java
core/src/main/java/org/geysermc/geyser/entity/type/AbstractArrowEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/AreaEffectCloudEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/BoatEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/ChestBoatEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/CommandBlockMinecartEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/DefaultBlockMinecartEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/EnderCrystalEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/Entity.java
core/src/main/java/org/geysermc/geyser/entity/type/EvokerFangsEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/ExpOrbEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/FallingBlockEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/FireballEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/FireworkEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/FishingHookEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/FurnaceMinecartEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/InteractionEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/ItemEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/ItemFrameEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/LeashKnotEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/LightningEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/LivingEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/MinecartEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/PaintingEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/SpawnerMinecartEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/TNTEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/TextDisplayEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/ThrowableEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/ThrowableItemEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/ThrownPotionEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/Tickable.java
core/src/main/java/org/geysermc/geyser/entity/type/TippedArrowEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/TridentEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/WitherSkullEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/AbstractFishEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/AgeableEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/AllayEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/AmbientEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/ArmorStandEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/BatEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/CreatureEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/DolphinEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/FlyingEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/GlowSquidEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/GolemEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/IronGolemEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/MagmaCubeEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/MobEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/SlimeEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/SnowGolemEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/SquidEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/TadpoleEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/WaterEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/AnimalEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/AxolotlEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/BeeEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/ChickenEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/CowEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/FoxEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/FrogEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/GoatEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/HoglinEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/MooshroomEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/OcelotEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/PandaEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/PigEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/PolarBearEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/PufferFishEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/RabbitEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/SheepEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/SnifferEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/StriderEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/TropicalFishEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/TurtleEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/horse/AbstractHorseEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/horse/CamelEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/horse/ChestedHorseEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/horse/HorseEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/horse/LlamaEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/horse/SkeletonHorseEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/horse/TraderLlamaEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/horse/ZombieHorseEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/tameable/CatEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/tameable/ParrotEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/tameable/TameableEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/animal/tameable/WolfEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/merchant/AbstractMerchantEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/merchant/VillagerEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/AbstractSkeletonEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/BasePiglinEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/BlazeEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/CreeperEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/ElderGuardianEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/EnderDragonEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/EnderDragonPartEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/EndermanEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/GhastEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/GiantEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/GuardianEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/MonsterEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/PhantomEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/PiglinEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/ShulkerEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/SkeletonEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/SpiderEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/VexEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/WardenEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/WitherEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/ZoglinEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/ZombieEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/ZombieVillagerEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/ZombifiedPiglinEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/raid/AbstractIllagerEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/raid/PillagerEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/raid/RaidParticipantEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/raid/SpellcasterIllagerEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/living/monster/raid/VindicatorEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/player/PlayerEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/player/SessionPlayerEntity.java
core/src/main/java/org/geysermc/geyser/entity/type/player/SkullPlayerEntity.java
core/src/main/java/org/geysermc/geyser/erosion/AbstractGeyserboundPacketHandler.java
core/src/main/java/org/geysermc/geyser/erosion/GeyserErosionPacketSender.java
core/src/main/java/org/geysermc/geyser/erosion/GeyserboundHandshakePacketHandler.java
core/src/main/java/org/geysermc/geyser/erosion/GeyserboundPacketHandlerImpl.java
core/src/main/java/org/geysermc/geyser/erosion/UnixSocketClientListener.java
core/src/main/java/org/geysermc/geyser/event/GeyserEventBus.java
core/src/main/java/org/geysermc/geyser/event/GeyserEventRegistrar.java
core/src/main/java/org/geysermc/geyser/event/GeyserEventSubscriber.java
core/src/main/java/org/geysermc/geyser/event/type/GeyserBedrockPingEventImpl.java
core/src/main/java/org/geysermc/geyser/event/type/GeyserDefineCommandsEventImpl.java
core/src/main/java/org/geysermc/geyser/event/type/GeyserDefineCustomItemsEventImpl.java
core/src/main/java/org/geysermc/geyser/event/type/SessionLoadResourcePacksEventImpl.java
core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionClassLoader.java
core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionContainer.java
core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionDescription.java
core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionLoader.java
core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionLogger.java
core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionManager.java
core/src/main/java/org/geysermc/geyser/extension/command/GeyserExtensionCommand.java
core/src/main/java/org/geysermc/geyser/extension/event/GeyserExtensionEventBus.java
core/src/main/java/org/geysermc/geyser/inventory/AnvilContainer.java
core/src/main/java/org/geysermc/geyser/inventory/BeaconContainer.java
core/src/main/java/org/geysermc/geyser/inventory/BedrockContainerSlot.java
core/src/main/java/org/geysermc/geyser/inventory/CartographyContainer.java
core/src/main/java/org/geysermc/geyser/inventory/Container.java
core/src/main/java/org/geysermc/geyser/inventory/CrafterContainer.java
core/src/main/java/org/geysermc/geyser/inventory/EnchantingContainer.java
core/src/main/java/org/geysermc/geyser/inventory/Generic3X3Container.java
core/src/main/java/org/geysermc/geyser/inventory/GeyserEnchantOption.java
core/src/main/java/org/geysermc/geyser/inventory/GeyserItemStack.java
core/src/main/java/org/geysermc/geyser/inventory/Inventory.java
core/src/main/java/org/geysermc/geyser/inventory/LecternContainer.java
core/src/main/java/org/geysermc/geyser/inventory/MerchantContainer.java
core/src/main/java/org/geysermc/geyser/inventory/PlayerInventory.java
core/src/main/java/org/geysermc/geyser/inventory/SlotType.java
core/src/main/java/org/geysermc/geyser/inventory/StonecutterContainer.java
core/src/main/java/org/geysermc/geyser/inventory/click/Click.java
core/src/main/java/org/geysermc/geyser/inventory/click/ClickPlan.java
core/src/main/java/org/geysermc/geyser/inventory/holder/BlockInventoryHolder.java
core/src/main/java/org/geysermc/geyser/inventory/holder/InventoryHolder.java
core/src/main/java/org/geysermc/geyser/inventory/item/Enchantment.java
core/src/main/java/org/geysermc/geyser/inventory/item/Potion.java
core/src/main/java/org/geysermc/geyser/inventory/item/StoredItemMappings.java
core/src/main/java/org/geysermc/geyser/inventory/item/TippedArrowPotion.java
core/src/main/java/org/geysermc/geyser/inventory/recipe/GeyserRecipe.java
core/src/main/java/org/geysermc/geyser/inventory/recipe/GeyserShapedRecipe.java
core/src/main/java/org/geysermc/geyser/inventory/recipe/GeyserShapelessRecipe.java
core/src/main/java/org/geysermc/geyser/inventory/recipe/GeyserStonecutterData.java
core/src/main/java/org/geysermc/geyser/inventory/recipe/TrimRecipe.java
core/src/main/java/org/geysermc/geyser/inventory/updater/AnvilInventoryUpdater.java
core/src/main/java/org/geysermc/geyser/inventory/updater/ChestInventoryUpdater.java
core/src/main/java/org/geysermc/geyser/inventory/updater/ContainerInventoryUpdater.java
core/src/main/java/org/geysermc/geyser/inventory/updater/CrafterInventoryUpdater.java
core/src/main/java/org/geysermc/geyser/inventory/updater/HorseInventoryUpdater.java
core/src/main/java/org/geysermc/geyser/inventory/updater/InventoryUpdater.java
core/src/main/java/org/geysermc/geyser/inventory/updater/UIInventoryUpdater.java
core/src/main/java/org/geysermc/geyser/item/ArmorMaterial.java
core/src/main/java/org/geysermc/geyser/item/DyeableLeatherItem.java
core/src/main/java/org/geysermc/geyser/item/GeyserCustomItemData.java
core/src/main/java/org/geysermc/geyser/item/GeyserCustomItemOptions.java
core/src/main/java/org/geysermc/geyser/item/GeyserCustomMappingData.java
core/src/main/java/org/geysermc/geyser/item/GeyserNonVanillaCustomItemData.java
core/src/main/java/org/geysermc/geyser/item/Items.java
core/src/main/java/org/geysermc/geyser/item/components/ToolTier.java
core/src/main/java/org/geysermc/geyser/item/components/WearableSlot.java
core/src/main/java/org/geysermc/geyser/item/exception/InvalidCustomMappingsFileException.java
core/src/main/java/org/geysermc/geyser/item/type/ArmorItem.java
core/src/main/java/org/geysermc/geyser/item/type/ArrowItem.java
core/src/main/java/org/geysermc/geyser/item/type/AxolotlBucketItem.java
core/src/main/java/org/geysermc/geyser/item/type/BannerItem.java
core/src/main/java/org/geysermc/geyser/item/type/BlockItem.java
core/src/main/java/org/geysermc/geyser/item/type/BoatItem.java
core/src/main/java/org/geysermc/geyser/item/type/ChestItem.java
core/src/main/java/org/geysermc/geyser/item/type/CompassItem.java
core/src/main/java/org/geysermc/geyser/item/type/CrossbowItem.java
core/src/main/java/org/geysermc/geyser/item/type/DecoratedPotItem.java
core/src/main/java/org/geysermc/geyser/item/type/DyeItem.java
core/src/main/java/org/geysermc/geyser/item/type/DyeableArmorItem.java
core/src/main/java/org/geysermc/geyser/item/type/DyeableHorseArmorItem.java
core/src/main/java/org/geysermc/geyser/item/type/ElytraItem.java
core/src/main/java/org/geysermc/geyser/item/type/EnchantedBookItem.java
core/src/main/java/org/geysermc/geyser/item/type/FilledMapItem.java
core/src/main/java/org/geysermc/geyser/item/type/FireworkRocketItem.java
core/src/main/java/org/geysermc/geyser/item/type/FireworkStarItem.java
core/src/main/java/org/geysermc/geyser/item/type/FishingRodItem.java
core/src/main/java/org/geysermc/geyser/item/type/FlowerItem.java
core/src/main/java/org/geysermc/geyser/item/type/GoatHornItem.java
core/src/main/java/org/geysermc/geyser/item/type/Item.java
core/src/main/java/org/geysermc/geyser/item/type/MapItem.java
core/src/main/java/org/geysermc/geyser/item/type/PlayerHeadItem.java
core/src/main/java/org/geysermc/geyser/item/type/PotionItem.java
core/src/main/java/org/geysermc/geyser/item/type/ShieldItem.java
core/src/main/java/org/geysermc/geyser/item/type/ShulkerBoxItem.java
core/src/main/java/org/geysermc/geyser/item/type/SpawnEggItem.java
core/src/main/java/org/geysermc/geyser/item/type/TieredItem.java
core/src/main/java/org/geysermc/geyser/item/type/TippedArrowItem.java
core/src/main/java/org/geysermc/geyser/item/type/TropicalFishBucketItem.java
core/src/main/java/org/geysermc/geyser/item/type/WritableBookItem.java
core/src/main/java/org/geysermc/geyser/item/type/WrittenBookItem.java
core/src/main/java/org/geysermc/geyser/level/BedrockDimension.java
core/src/main/java/org/geysermc/geyser/level/BedrockMapIcon.java
core/src/main/java/org/geysermc/geyser/level/FireworkColor.java
core/src/main/java/org/geysermc/geyser/level/GameRule.java
core/src/main/java/org/geysermc/geyser/level/GeyserAdvancement.java
core/src/main/java/org/geysermc/geyser/level/GeyserWorldManager.java
core/src/main/java/org/geysermc/geyser/level/JavaDimension.java
core/src/main/java/org/geysermc/geyser/level/MapColor.java
core/src/main/java/org/geysermc/geyser/level/PaintingType.java
core/src/main/java/org/geysermc/geyser/level/WorldManager.java
core/src/main/java/org/geysermc/geyser/level/block/BlockStateValues.java
core/src/main/java/org/geysermc/geyser/level/block/DoubleChestValue.java
core/src/main/java/org/geysermc/geyser/level/block/GeyserCustomBlockComponents.java
core/src/main/java/org/geysermc/geyser/level/block/GeyserCustomBlockData.java
core/src/main/java/org/geysermc/geyser/level/block/GeyserCustomBlockProperty.java
core/src/main/java/org/geysermc/geyser/level/block/GeyserCustomBlockState.java
core/src/main/java/org/geysermc/geyser/level/block/GeyserGeometryComponent.java
core/src/main/java/org/geysermc/geyser/level/block/GeyserJavaBlockState.java
core/src/main/java/org/geysermc/geyser/level/block/GeyserMaterialInstance.java
core/src/main/java/org/geysermc/geyser/level/block/GeyserNonVanillaCustomBlockData.java
core/src/main/java/org/geysermc/geyser/level/chunk/BlockStorage.java
core/src/main/java/org/geysermc/geyser/level/chunk/GeyserChunk.java
core/src/main/java/org/geysermc/geyser/level/chunk/GeyserChunkSection.java
core/src/main/java/org/geysermc/geyser/level/chunk/bitarray/BitArray.java
core/src/main/java/org/geysermc/geyser/level/chunk/bitarray/BitArrayVersion.java
core/src/main/java/org/geysermc/geyser/level/chunk/bitarray/PaddedBitArray.java
core/src/main/java/org/geysermc/geyser/level/chunk/bitarray/Pow2BitArray.java
core/src/main/java/org/geysermc/geyser/level/chunk/bitarray/SingletonBitArray.java
core/src/main/java/org/geysermc/geyser/level/physics/Axis.java
core/src/main/java/org/geysermc/geyser/level/physics/BoundingBox.java
core/src/main/java/org/geysermc/geyser/level/physics/CollisionManager.java
core/src/main/java/org/geysermc/geyser/level/physics/Direction.java
core/src/main/java/org/geysermc/geyser/level/physics/PistonBehavior.java
core/src/main/java/org/geysermc/geyser/network/CIDRMatcher.java
core/src/main/java/org/geysermc/geyser/network/GameProtocol.java
core/src/main/java/org/geysermc/geyser/network/GeyserBedrockPeer.java
core/src/main/java/org/geysermc/geyser/network/GeyserServerInitializer.java
core/src/main/java/org/geysermc/geyser/network/LoggingPacketHandler.java
core/src/main/java/org/geysermc/geyser/network/UpstreamPacketHandler.java
core/src/main/java/org/geysermc/geyser/network/netty/ChannelWrapper.java
core/src/main/java/org/geysermc/geyser/network/netty/DefaultChannelPipelinePublic.java
core/src/main/java/org/geysermc/geyser/network/netty/GeyserInjector.java
core/src/main/java/org/geysermc/geyser/network/netty/GeyserServer.java
core/src/main/java/org/geysermc/geyser/network/netty/LocalChannelWithRemoteAddress.java
core/src/main/java/org/geysermc/geyser/network/netty/LocalChannelWrapper.java
core/src/main/java/org/geysermc/geyser/network/netty/LocalServerChannelWrapper.java
core/src/main/java/org/geysermc/geyser/network/netty/LocalSession.java
core/src/main/java/org/geysermc/geyser/network/netty/handler/RakConnectionRequestHandler.java
core/src/main/java/org/geysermc/geyser/network/netty/handler/RakPingHandler.java
core/src/main/java/org/geysermc/geyser/network/netty/proxy/ProxyProtocolDecoder.java
core/src/main/java/org/geysermc/geyser/network/netty/proxy/ProxyServerHandler.java
core/src/main/java/org/geysermc/geyser/pack/GeyserResourcePack.java
core/src/main/java/org/geysermc/geyser/pack/GeyserResourcePackManifest.java
core/src/main/java/org/geysermc/geyser/pack/SkullResourcePackManager.java
core/src/main/java/org/geysermc/geyser/pack/path/GeyserPathPackCodec.java
core/src/main/java/org/geysermc/geyser/ping/GeyserLegacyPingPassthrough.java
core/src/main/java/org/geysermc/geyser/ping/GeyserPingInfo.java
core/src/main/java/org/geysermc/geyser/ping/IGeyserPingPassthrough.java
core/src/main/java/org/geysermc/geyser/registry/AbstractMappedRegistry.java
core/src/main/java/org/geysermc/geyser/registry/ArrayRegistry.java
core/src/main/java/org/geysermc/geyser/registry/BlockRegistries.java
core/src/main/java/org/geysermc/geyser/registry/DeferredRegistry.java
core/src/main/java/org/geysermc/geyser/registry/IRegistry.java
core/src/main/java/org/geysermc/geyser/registry/IntMappedRegistry.java
core/src/main/java/org/geysermc/geyser/registry/MappedRegistry.java
core/src/main/java/org/geysermc/geyser/registry/PacketTranslatorRegistry.java
core/src/main/java/org/geysermc/geyser/registry/Registries.java
core/src/main/java/org/geysermc/geyser/registry/Registry.java
core/src/main/java/org/geysermc/geyser/registry/SimpleMappedRegistry.java
core/src/main/java/org/geysermc/geyser/registry/SimpleRegistry.java
core/src/main/java/org/geysermc/geyser/registry/VersionedRegistry.java
core/src/main/java/org/geysermc/geyser/registry/loader/AnnotatedRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/BiomeIdentifierRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/BlockEntityRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/CollisionRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/EffectRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/EnchantmentRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/MultiResourceRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/NbtRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/ParticleTypesRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/PotionMixRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/ProviderRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/RegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/RegistryLoaders.java
core/src/main/java/org/geysermc/geyser/registry/loader/ResourcePackLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/SoundEventsRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/SoundRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/loader/SoundTranslatorRegistryLoader.java
core/src/main/java/org/geysermc/geyser/registry/mappings/MappingsConfigReader.java
core/src/main/java/org/geysermc/geyser/registry/mappings/util/CustomBlockComponentsMapping.java
core/src/main/java/org/geysermc/geyser/registry/mappings/util/CustomBlockMapping.java
core/src/main/java/org/geysermc/geyser/registry/mappings/util/CustomBlockStateBuilderMapping.java
core/src/main/java/org/geysermc/geyser/registry/mappings/util/CustomBlockStateMapping.java
core/src/main/java/org/geysermc/geyser/registry/mappings/versions/MappingsReader.java
core/src/main/java/org/geysermc/geyser/registry/mappings/versions/MappingsReader_v1.java
core/src/main/java/org/geysermc/geyser/registry/populator/BlockRegistryPopulator.java
core/src/main/java/org/geysermc/geyser/registry/populator/Conversion630_622.java
core/src/main/java/org/geysermc/geyser/registry/populator/CreativeItemRegistryPopulator.java
core/src/main/java/org/geysermc/geyser/registry/populator/CustomBlockRegistryPopulator.java
core/src/main/java/org/geysermc/geyser/registry/populator/CustomItemRegistryPopulator.java
core/src/main/java/org/geysermc/geyser/registry/populator/CustomSkullRegistryPopulator.java
core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java
core/src/main/java/org/geysermc/geyser/registry/populator/PacketRegistryPopulator.java
core/src/main/java/org/geysermc/geyser/registry/populator/RecipeRegistryPopulator.java
core/src/main/java/org/geysermc/geyser/registry/provider/ProviderSupplier.java
core/src/main/java/org/geysermc/geyser/registry/type/BlockMapping.java
core/src/main/java/org/geysermc/geyser/registry/type/BlockMappings.java
core/src/main/java/org/geysermc/geyser/registry/type/CustomSkull.java
core/src/main/java/org/geysermc/geyser/registry/type/EnchantmentData.java
core/src/main/java/org/geysermc/geyser/registry/type/GeyserBedrockBlock.java
core/src/main/java/org/geysermc/geyser/registry/type/GeyserItemDefinition.java
core/src/main/java/org/geysermc/geyser/registry/type/GeyserMappingItem.java
core/src/main/java/org/geysermc/geyser/registry/type/ItemMapping.java
core/src/main/java/org/geysermc/geyser/registry/type/ItemMappings.java
core/src/main/java/org/geysermc/geyser/registry/type/NonVanillaItemRegistration.java
core/src/main/java/org/geysermc/geyser/registry/type/PaletteItem.java
core/src/main/java/org/geysermc/geyser/registry/type/ParticleMapping.java
core/src/main/java/org/geysermc/geyser/registry/type/SoundMapping.java
core/src/main/java/org/geysermc/geyser/scoreboard/Objective.java
core/src/main/java/org/geysermc/geyser/scoreboard/Score.java
core/src/main/java/org/geysermc/geyser/scoreboard/Scoreboard.java
core/src/main/java/org/geysermc/geyser/scoreboard/ScoreboardUpdater.java
core/src/main/java/org/geysermc/geyser/scoreboard/Team.java
core/src/main/java/org/geysermc/geyser/scoreboard/UpdateType.java
core/src/main/java/org/geysermc/geyser/session/DownstreamSession.java
core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
core/src/main/java/org/geysermc/geyser/session/PendingMicrosoftAuthentication.java
core/src/main/java/org/geysermc/geyser/session/SessionManager.java
core/src/main/java/org/geysermc/geyser/session/UpstreamSession.java
core/src/main/java/org/geysermc/geyser/session/auth/AuthData.java
core/src/main/java/org/geysermc/geyser/session/auth/BedrockClientData.java
core/src/main/java/org/geysermc/geyser/session/cache/AdvancementsCache.java
core/src/main/java/org/geysermc/geyser/session/cache/BookEditCache.java
core/src/main/java/org/geysermc/geyser/session/cache/BossBar.java
core/src/main/java/org/geysermc/geyser/session/cache/ChunkCache.java
core/src/main/java/org/geysermc/geyser/session/cache/EntityCache.java
core/src/main/java/org/geysermc/geyser/session/cache/EntityEffectCache.java
core/src/main/java/org/geysermc/geyser/session/cache/FormCache.java
core/src/main/java/org/geysermc/geyser/session/cache/LodestoneCache.java
core/src/main/java/org/geysermc/geyser/session/cache/PistonCache.java
core/src/main/java/org/geysermc/geyser/session/cache/PreferencesCache.java
core/src/main/java/org/geysermc/geyser/session/cache/SkullCache.java
core/src/main/java/org/geysermc/geyser/session/cache/TagCache.java
core/src/main/java/org/geysermc/geyser/session/cache/TeleportCache.java
core/src/main/java/org/geysermc/geyser/session/cache/WorldBorder.java
core/src/main/java/org/geysermc/geyser/session/cache/WorldCache.java
core/src/main/java/org/geysermc/geyser/skin/FakeHeadProvider.java
core/src/main/java/org/geysermc/geyser/skin/FloodgateSkinUploader.java
core/src/main/java/org/geysermc/geyser/skin/ProvidedSkins.java
core/src/main/java/org/geysermc/geyser/skin/SkinManager.java
core/src/main/java/org/geysermc/geyser/skin/SkinProvider.java
core/src/main/java/org/geysermc/geyser/skin/SkullSkinManager.java
core/src/main/java/org/geysermc/geyser/text/AsteriskSerializer.java
core/src/main/java/org/geysermc/geyser/text/ChatColor.java
core/src/main/java/org/geysermc/geyser/text/ChatTypeEntry.java
core/src/main/java/org/geysermc/geyser/text/DummyLegacyHoverEventSerializer.java
core/src/main/java/org/geysermc/geyser/text/GeyserLocale.java
core/src/main/java/org/geysermc/geyser/text/GsonComponentSerializerWrapper.java
core/src/main/java/org/geysermc/geyser/text/MinecraftLocale.java
core/src/main/java/org/geysermc/geyser/text/MinecraftTranslationRegistry.java
core/src/main/java/org/geysermc/geyser/text/TextDecoration.java
core/src/main/java/org/geysermc/geyser/translator/collision/BlockCollision.java
core/src/main/java/org/geysermc/geyser/translator/collision/CollisionRemapper.java
core/src/main/java/org/geysermc/geyser/translator/collision/DirtPathCollision.java
core/src/main/java/org/geysermc/geyser/translator/collision/DoorCollision.java
core/src/main/java/org/geysermc/geyser/translator/collision/GlassPaneAndIronBarsCollision.java
core/src/main/java/org/geysermc/geyser/translator/collision/OtherCollision.java
core/src/main/java/org/geysermc/geyser/translator/collision/ScaffoldingCollision.java
core/src/main/java/org/geysermc/geyser/translator/collision/SnowCollision.java
core/src/main/java/org/geysermc/geyser/translator/collision/SolidCollision.java
core/src/main/java/org/geysermc/geyser/translator/collision/TrapdoorCollision.java
core/src/main/java/org/geysermc/geyser/translator/entity/EntityMetadataTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/AbstractBlockInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/AnvilInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/BaseInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/BeaconInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/BrewingInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/CartographyInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/CrafterInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/CraftingInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/EnchantingInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/Generic3X3InventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/GrindstoneInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/HopperInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/InventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/LecternInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/LoomInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/MerchantInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/OldSmithingTableTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/PlayerInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/ShulkerInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/SmithingInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/StonecutterInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/chest/ChestInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/chest/DoubleChestInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/chest/SingleChestInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/furnace/AbstractFurnaceInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/furnace/BlastFurnaceInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/furnace/FurnaceInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/furnace/SmokerInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/horse/AbstractHorseInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/horse/ChestedHorseInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/horse/DonkeyInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/horse/HorseInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/horse/LlamaInventoryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/item/CustomItemTranslator.java
core/src/main/java/org/geysermc/geyser/translator/inventory/item/ItemTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/BiomeTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/BannerBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/BeaconBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/BedBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/BedrockOnlyBlockEntity.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/BlockEntity.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/BlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/BrushableBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/CampfireBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/CommandBlockBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/DecoratedPotBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/DoubleChestBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/EmptyBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/EndGatewayBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/FlowerPotBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/HangingSignBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/JigsawBlockBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/PistonBlockEntity.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/PistonBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/RequiresBlockState.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/ShulkerBoxBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/SignBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/SkullBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/SpawnerBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/block/entity/TrialSpawnerBlockEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/event/LevelEventTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/event/PlaySoundEventTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/event/SoundEventEventTranslator.java
core/src/main/java/org/geysermc/geyser/translator/level/event/SoundLevelEventTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/PacketTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/Translator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockAnimateTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockBlockEntityDataTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockBlockPickRequestTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockBookEditTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockCommandBlockUpdateTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockCommandRequestTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockContainerCloseTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockEmoteListTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockEntityPickRequestTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockFilterTextTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockInventoryTransactionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockItemFrameDropItemTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockItemStackRequestTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockLecternUpdateTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockMapInfoRequestTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockMobEquipmentTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockMoveEntityAbsoluteTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockNetworkStackLatencyTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockPacketViolationWarningTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockPlayerInputTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockPositionTrackingDBClientRequestTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockRequestAbilityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockRequestChunkRadiusTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockRespawnTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockServerSettingsRequestTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockSetLocalPlayerAsInitializedTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockShowCreditsTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockTextTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockToggleCrafterSlotRequestTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/BedrockEntityEventTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockActionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockEmoteTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockInteractTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockMovePlayerTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockRequestPermissionsPacket.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockRiderJumpTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockSetDefaultGameTypeTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockSetDifficultyTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockSetPlayerGameTypeTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockSetPlayerInventoryOptionsTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/world/BedrockLevelSoundEventTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaAwardStatsTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaBossEventTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaChangeDifficultyTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaClientboundRecipesTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaClientboundResourcePackPushPacket.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaCommandsTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaCustomPayloadTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaCustomQueryTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaDisconnectTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaDisguisedChatTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaGameProfileTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaKeepAliveTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaLoginDisconnectTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaLoginTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaPingTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaPlayerChatTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaRegistryDataTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaRespawnTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaSelectAdvancementsTabTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaSystemChatTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateAdvancementsTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateTagsTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaAnimateTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaDamageEventTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaEntityEventTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaMoveEntityPosRotTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaMoveEntityPosTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaMoveEntityRotTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaMoveVehicleTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaRemoveEntitiesTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaRemoveMobEffectTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaRotateHeadTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaSetEntityDataTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaSetEntityLinkTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaSetEntityMotionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaSetEquipmentTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaSetPassengersTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaSoundEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaTakeItemEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaTeleportEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaUpdateAttributesTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaUpdateMobEffectTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/player/JavaBlockChangedAckTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/player/JavaPlayerAbilitiesTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/player/JavaPlayerCombatKillTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/player/JavaPlayerInfoRemoveTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/player/JavaPlayerInfoUpdateTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/player/JavaPlayerLookAtTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/player/JavaPlayerPositionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/player/JavaSetCarriedItemTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/player/JavaSetExperienceTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/player/JavaSetHealthTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/spawn/JavaAddEntityTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/spawn/JavaAddExperienceOrbTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaContainerCloseTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaContainerSetContentTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaContainerSetDataTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaContainerSetSlotTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaHorseScreenOpenTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaMerchantOffersTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaOpenScreenTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockDestructionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockEntityDataTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockEventTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockUpdateTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaChunkBatchFinishedTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaCooldownTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaExplodeTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaForgetLevelChunkTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaGameEventTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaLevelChunkWithLightTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaLevelEventTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaLevelParticlesTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaMapItemDataTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaOpenSignEditorTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaSectionBlocksUpdateTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaSetChunkCacheCenterTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaSetChunkCacheRadiusTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaSetDefaultSpawnPositionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaSetTimeTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaSoundTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaStopSoundTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/border/JavaInitializeBorderTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/border/JavaSetBorderCenterTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/border/JavaSetBorderLerpSizeTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/border/JavaSetBorderSizeTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/border/JavaSetBorderWarningDelayTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/border/JavaSetBorderWarningDistanceTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/scoreboard/JavaResetScorePacket.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/scoreboard/JavaSetDisplayObjectiveTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/scoreboard/JavaSetObjectiveTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/scoreboard/JavaSetPlayerTeamTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/scoreboard/JavaSetScoreTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/title/JavaClearTitlesTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/title/JavaSetActionBarTextTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/title/JavaSetSubtitleTextTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/title/JavaSetTitleTextTranslator.java
core/src/main/java/org/geysermc/geyser/translator/protocol/java/title/JavaSetTitlesAnimationTranslator.java
core/src/main/java/org/geysermc/geyser/translator/sound/BlockSoundInteractionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/sound/SoundInteractionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/sound/SoundTranslator.java
core/src/main/java/org/geysermc/geyser/translator/sound/block/BucketSoundInteractionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/sound/block/ComparatorSoundInteractionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/sound/block/DoorSoundInteractionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/sound/block/FlintAndSteelInteractionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/sound/block/GrassPathInteractionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/sound/block/HoeInteractionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/sound/block/LeverSoundInteractionTranslator.java
core/src/main/java/org/geysermc/geyser/translator/text/MessageTranslator.java
core/src/main/java/org/geysermc/geyser/util/AssetUtils.java
core/src/main/java/org/geysermc/geyser/util/AttributeUtils.java
core/src/main/java/org/geysermc/geyser/util/BlockEntityUtils.java
core/src/main/java/org/geysermc/geyser/util/BlockUtils.java
core/src/main/java/org/geysermc/geyser/util/ChunkUtils.java
core/src/main/java/org/geysermc/geyser/util/CooldownUtils.java
core/src/main/java/org/geysermc/geyser/util/CpuUtils.java
core/src/main/java/org/geysermc/geyser/util/DimensionUtils.java
core/src/main/java/org/geysermc/geyser/util/EntityUtils.java
core/src/main/java/org/geysermc/geyser/util/FileUtils.java
core/src/main/java/org/geysermc/geyser/util/InteractionResult.java
core/src/main/java/org/geysermc/geyser/util/InteractiveTag.java
core/src/main/java/org/geysermc/geyser/util/InventoryUtils.java
core/src/main/java/org/geysermc/geyser/util/ItemUtils.java
core/src/main/java/org/geysermc/geyser/util/JavaCodecUtil.java
core/src/main/java/org/geysermc/geyser/util/LoginEncryptionUtils.java
core/src/main/java/org/geysermc/geyser/util/LoopbackUtil.java
core/src/main/java/org/geysermc/geyser/util/MathUtils.java
core/src/main/java/org/geysermc/geyser/util/Metrics.java
core/src/main/java/org/geysermc/geyser/util/NewsHandler.java
core/src/main/java/org/geysermc/geyser/util/PluginMessageUtils.java
core/src/main/java/org/geysermc/geyser/util/SettingsUtils.java
core/src/main/java/org/geysermc/geyser/util/SignUtils.java
core/src/main/java/org/geysermc/geyser/util/SoundUtils.java
core/src/main/java/org/geysermc/geyser/util/StatisticFormatters.java
core/src/main/java/org/geysermc/geyser/util/StatisticsUtils.java
core/src/main/java/org/geysermc/geyser/util/VersionCheckUtils.java
core/src/main/java/org/geysermc/geyser/util/WebUtils.java
core/src/main/java/org/geysermc/geyser/util/collection/FixedInt2BooleanMap.java
core/src/main/java/org/geysermc/geyser/util/collection/FixedInt2ByteMap.java
core/src/main/java/org/geysermc/geyser/util/collection/FixedInt2IntMap.java
core/src/main/java/org/geysermc/geyser/util/collection/LecternHasBookMap.java
core/src/main/java/org/geysermc/geyser/util/collection/package-info.java
<unknown>




importCpg("/data/DataLACP/wangke/recorebench/workspace/Geyser/cpg.bin.zip")
cpg.method.filter(_.fullName == "java.util.Collections.singletonList:java.util.List(java.lang.Object)").headOption
cpg.method.filter(_.fullName == "org.cloudburstmc.protocol.bedrock.packet.CraftingDataPacket.getCraftingData:<unresolvedSignature>(0)").headOption
cpg.method.filter(_.fullName == "<unresolvedNamespace>.add:<unresolvedSignature>(1)").headOption
cpg.call.filter(_.name == "add").l
cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.name == "addSpecialRecipesIdentifiers").l

cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.name == "add").lineNumber(411).plotDotAst

cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.name == "add").lineNumber(411).astParent.astParent.astParent.astParent.dotAst.l
cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.name == "add").lineNumber(411).astParent.astParent.astParent.astParent.dotAst.l #> "/data/DataLACP/wangke/recorebench/workspace/Geyser/ast1.dot"
cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "Registries").lineNumber(147).astChildren.l
cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.name == "get").lineNumber(147).l



cpg.call.filter(call => call.code == "squashedOptions.computeIfAbsent(Collections.singleton(ItemDescriptorWithCount.EMPTY), k -> new IntOpenHashSet()).add(i)").l

cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.name == "get").lineNumber(200).astChildren.l
cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.name == "addSpecialRecipesIdentifiers").filter(call => call.astChildren.head.name == "this").l
cpg.call.id(30064836378L).l
cpg.call.filter(call => call.id == 68719527881L).l
cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.name == "addSpecialRecipesIdentifiers").l
cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.name == "addSpecialRecipesIdentifiers").map(call => List(call, call.astChildren.head))

def source = cpg.local.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).name("recipeMap").head
def source = cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).name("recipeMap").lineNumber(118).l
def sink = cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).name("recipeMap").lineNumber(240).l
sink.reachableByFlows(source).p
sink.reachableBy(source).l

cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.name == "stoneCuttingData").id
cpg.call.where(_.file.nameExact(\"{self.rel_file_path}\")).filter(call => call.name == \"{callee}\").map(call => (call, call.astChildren.head.code.l))
cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.name == "getData").map(call => (call, call.astChildren.head.code.l))

cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.name == "get").lineNumber(147).astParent.astParent.astParent.astParent.astParent.astParent.astParent.astParent.astParent.astParent.astParent.astParent.head.dotAst.l #> "/data/DataLACP/wangke/recorebench/workspace/Geyser/ast1.dot"
cpg.fieldIdentifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).lineNumber(146)
cpg.fieldIdentifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).lineNumber(146).astParent.l
cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).code("Registries.JAVA_ITEMS").l

cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).name("ItemStack")
cpg.typeDecl.fullName("org.geysermc.geyser.registry.SimpleRegistry").l
cpg.local.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).name("stonecutterRecipeMap").l
cpg.local.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).code("ItemStack.*").l
cpg.annotation.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).name("Translator").l

cpg.method.filter(_.fullName == "core/src/main/java/org.geysermc.geyser.translator.protocol.Translator").l
cpg.typeDecl.filter(_.fullName == "core/src/main/java/org.geysermc.geyser.translator.protocol.Translator").l
cpg.typeDecl.fullName("org.geysermc.geyser.translator.protocol.Translator").l

'cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).code("length").l.toJsonPretty #> "/data/DataLACP/wangke/recorebench/workspace/Geyser/tmp.json"'
'cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).code("stoneCuttingData.getIngredient().getOptions().length").l.toJsonPretty #> "/data/DataLACP/wangke/recorebench/workspace/Geyser/tmp.json"'
stoneCuttingData.getIngredient().getOptions().length
cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.code == "stoneCuttingData.getIngredient().getOptions().length").l
cpg.call.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(call => call.code == "stoneCuttingData.getIngredient().getOptions().length").l

/data/DataLACP/wangke/recorebench/repo/repo/dynamic-tp/core/src/main/java/com/dtp/core/context/BaseNotifyCtx.java

/data/DataLACP/wangke/recorebench/repo/repo/zuul/zuul-core/src/main/java/com/netflix/zuul/netty/filter/BaseZuulFilterRunner.java
'formal_parameter'


/data/DataLACP/wangke/recorebench/repo/repo/zuul/zuul-core/src/main/java/com/netflix/zuul/netty/filter/BaseZuulFilterRunner.java
/data/DataLACP/wangke/recorebench/repo/repo/traccar/src/main/java/org/traccar/protocol/SuntechProtocolDecoder.java




importCpg("/data/DataLACP/wangke/recorebench/workspace/Geyser/cpg.bin.zip")
/data/DataLACP/wangke/recorebench/repo/repo/Geyser/core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java


cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "recipeTypes").l
cpg.local.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "recipeTypes").headOption

def source = cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "recipeTypes").l
def sink = cpg.local.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "recipeTypes").l
sink.reachableByFlows(source).p

def source = cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "recipeTypes").head
def sink = cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "recipeTypes").l(1)
sink.reachableByFlows(source).p

def source = cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "recipeTypes").l
def sink = cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "recipeTypes").l
sink.reachableByFlows(source).p

def source = cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "craftingDataPacket").l
def sink = cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "craftingDataPacket").l
sink.reachableByFlows(source).p

def sink = cpg.methodParameterIn.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "session").lineNumber(88).l
def source = cpg.identifier.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "session").lineNumber(93).l
sink.reachableByFlows(source).p

cpg.methodParameterIn.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).filter(identifier => identifier.name == "session").l
cpg.all.label("param").l


cpg.method.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).lineNumber(407).l

cpg.method.where(_.file.nameExact("core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java")).lineNumber(407).l



/data/DataLACP/wangke/recorebench/repo/repo/resilience4j/resilience4j-framework-common/src/main/java/io/github/resilience4j/common/bulkhead/configuration/ThreadPoolBulkheadConfigurationProperties.java
importCpg("/data/DataLACP/wangke/recorebench/workspace/resilience4j/cpg.bin.zip")
cpg.file.nameExact("resilience4j-framework-common/src/main/java/io/github/resilience4j/common/bulkhead/configuration/ThreadPoolBulkheadConfigurationProperties.java").l

importCpg("/data/DataLACP/wangke/recorebench/workspace/graphql-java/cpg.bin.zip")
/data/DataLACP/wangke/recorebench/repo/repo/graphql-java/src/main/java/graphql/schema/GraphQLInputSchemaElement.java
cpg.file.nameExact("src/main/java/graphql/schema/GraphQLInputSchemaElement.java").l